# Generated by Django 3.0 on 2024-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='id',
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='snack',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
