# Generated by Django 3.0 on 2024-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('grouid', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
