# Generated by Django 3.0 on 2024-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_group',
            old_name='grouid',
            new_name='group_id',
        ),
    ]
