# Generated by Django 3.0 on 2024-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20240517_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='username',
            field=models.CharField(default='son_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='username',
            field=models.CharField(default='son_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='username',
            field=models.CharField(default='son_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='snack',
            name='username',
            field=models.CharField(default='son_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='username',
            field=models.CharField(default='son_1', max_length=100),
        ),
    ]
