# Generated by Django 3.0 on 2024-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20240517_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hot', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=1000)),
                ('username', models.CharField(default='son_1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hot', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=1000)),
                ('username', models.CharField(default='son_1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hot', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=1000)),
                ('username', models.CharField(default='son_1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hot', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=1000)),
                ('username', models.CharField(default='son_1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hot', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=1000)),
                ('username', models.CharField(default='son_1', max_length=100)),
            ],
        ),
    ]
