# Generated by Django 3.0 on 2024-05-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_breakfast_dinner_lunch_snack_sport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breakfast',
            unique_together={('date', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='dinner',
            unique_together={('date', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='lunch',
            unique_together={('date', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='snack',
            unique_together={('date', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='sport',
            unique_together={('date', 'username')},
        ),
    ]
