# Generated by Django 3.0 on 2024-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20240517_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='snack',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
