# Generated by Django 4.2.6 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0013_score_record_remove_user_id_remove_user_group_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="score_record",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="score_record",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
