# Generated by Django 4.2.11 on 2024-05-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_score_record_height_score_record_weight'),
        ('calculator', '0014_score_record_score_score_record_suggestion'),
    ]

    operations = [
    ]
